spring:
  application:
    name: tlias-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3308/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""  # 如果密码为空，填写空字符串
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true