spring:
  application:
    name: tlias-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3308/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""  # 如果密码为空，填写空字符串
  servlet:
    multipart:
      # 单个文件上传最大限制
      max-file-size: 10MB
      # 请求总大小限制
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

#配置事务管理日志规则、
#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#阿里云oss
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: java-test419
    region: cn-beijing